name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake=8.5.3
  - fastqc=0.12.1
  - fastp=0.23.4
  - bowtie2=2.5.3
  - samtools=1.19
  - metaphlan=4.1.0
  - megahit=1.2.9
  - metabat2=2.15
  - maxbin2=2.2.7
  - das_tool=1.1.7
  - diamond=2.1.9
  - checkm2=1.0.2
  - multiqc=1.21
  - pigz=2.8
